[env:esp32dev]
platform = espressif32 @ 7.0.1
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

lib_deps =
  olikraus/U8g2
  milesburton/DallasTemperature
  adafruit/DHT sensor library
  mobizt/FirebaseClient @ ^2.2.9
